title: "Adam’s AI + Python Blog"
description: "Exploring AI tools and data viz techniques."
baseurl: "/AdamsAiBlog"
url: "https://admilas.github.io"
theme: minima
markdown: kramdown
author:
  name: Adam
